-- Create monster_avatars table for shared avatar library
CREATE TABLE IF NOT EXISTS monster_avatars (
    id SERIAL PRIMARY KEY,
    monster_id VARCHAR(100) NOT NULL,  -- ID from monsters.json (e.g., "goblin")
    avatar_url TEXT NOT NULL,          -- URL to the avatar image
    created_by VARCHAR(100),           -- User ID who generated this avatar
    created_at TIMESTAMP DEFAULT NOW(),
    usage_count INTEGER DEFAULT 0     -- Track how many times this avatar has been used
);

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_monster_avatars_monster_id ON monster_avatars(monster_id);

-- Add comment
COMMENT ON TABLE monster_avatars IS 'Shared library of monster avatars generated by users';
COMMENT ON COLUMN monster_avatars.monster_id IS 'Reference to monster ID from monsters.json';
COMMENT ON COLUMN monster_avatars.usage_count IS 'Number of times this avatar has been selected by users';

