/**
 * Static Asset URL Resolver
 *
 * This utility handles resolving static asset URLs to either:
 * - OSS URLs (production, for images/music uploaded to Aliyun OSS)
 * - Local URLs (development, fallback)
 *
 * Usage:
 *   import { getAssetUrl } from '~/utils/asset-url';
 *   const imageUrl = getAssetUrl('assets/spell-icons/fireball.png');
 */

// Import the OSS mapping (generated by upload_static_assets_to_oss.py)
import ossMapping from '../../public/oss-asset-mapping.json';

// Type for the mapping
type OSSMapping = Record<string, string>;

// Cast imported mapping
const mapping: OSSMapping = ossMapping as OSSMapping;

// Base path for local assets - use empty string for SSR compatibility
// Vite sets BASE_URL at build time, but during SSR it may not be available
const BASE_PATH = typeof import.meta.env?.BASE_URL === 'string'
  ? import.meta.env.BASE_URL.replace(/\/$/, '')
  : '';

/**
 * Get the URL for a static asset
 *
 * @param localPath - The local path relative to /public, e.g., 'assets/spell-icons/fireball.png'
 * @returns The resolved URL (OSS if available, local otherwise)
 *
 * @example
 * // With OSS mapping: returns OSS URL
 * getAssetUrl('assets/spell-icons/fireball.png')
 * // => 'https://deepwood.oss-cn-beijing.aliyuncs.com/dnd-static/assets/spell-icons/fireball_abc123.webp'
 *
 * // Without OSS mapping: returns local URL
 * getAssetUrl('assets/spell-icons/fireball.png')
 * // => '/dnd/assets/spell-icons/fireball.png'
 */
export function getAssetUrl(localPath: string): string {
  // Normalize path (remove leading slash if present)
  const normalizedPath = localPath.startsWith('/') ? localPath.slice(1) : localPath;

  // Always use OSS URL if available in mapping (ensures SSR/CSR consistency)
  if (mapping[normalizedPath]) {
    return mapping[normalizedPath];
  }

  // Fallback to local path
  return `${BASE_PATH}/${normalizedPath}`;
}

/**
 * Get OSS URL directly (always returns OSS URL if available)
 * Use this when you specifically need the OSS URL regardless of environment
 */
export function getOSSUrl(localPath: string): string | null {
  const normalizedPath = localPath.startsWith('/') ? localPath.slice(1) : localPath;
  return mapping[normalizedPath] || null;
}

/**
 * Check if an asset has an OSS URL available
 */
export function hasOSSUrl(localPath: string): boolean {
  const normalizedPath = localPath.startsWith('/') ? localPath.slice(1) : localPath;
  return normalizedPath in mapping;
}

/**
 * Get the base URL for static assets (OSS domain if mapping exists, BASE_PATH otherwise)
 */
export function getStaticBaseUrl(): string {
  // Extract base URL from first OSS mapping entry if available
  const firstUrl = Object.values(mapping)[0];
  if (firstUrl) {
    try {
      const url = new URL(firstUrl);
      return `${url.protocol}//${url.host}`;
    } catch {
      // Invalid URL, fall through to BASE_PATH
    }
  }
  return BASE_PATH;
}

// Export the mapping for advanced use cases
export { mapping as ossMapping };
